GET http://localhost:8000/categories/

###
GET http://localhost:8000/categories/2f5c598c-6c50-4aaa-97f4-0800aac7a7de/

###
POST http://localhost:8000/categories/
Content-Type: application/json

{
    "name":"Movie"
}


###
PUT http://localhost:8000/categories/a99f3763-e272-4039-b930-5a3c9c4e6e98/
Content-Type: application/json

{
    "name":"Movie11111",
    "description": "some desc",
    "is_active": false
}

###
DELETE http://localhost:8000/categories/2f5c598c-6c50-4aaa-97f4-0800aac7a7de/
