GET http://localhost:8000/categories/

###
GET http://localhost:8000/categories/9411b83c-c773-4a09-85e3-600c6bfb33ca/

###
POST http://localhost:8000/categories/
Content-Type: application/json

{
    "name":"Movie"
}